spring:
  application:
    name: rabbitmq-listener

management:
  endpoints:
    web:
      exposure:
        include: health,beans
  health:
    rabbit:
      enabled: true
      show-details: always  # Set to 'always' to show more details


rabbitmq:
  host: ${host:localhost}
  port: ${port:5672}
  username: ${username:guest}
  password: ${password:guest}
  concurrentConsumers: ${concurrentConsumers:2}
  maxConcurrentConsumers: ${maxConcurrentConsumers:5}
  enableVirtualThreads: ${enableVirtualThreads:false}
  batchSize: ${batchSize:10}
  batchMaxWeight: ${batchMaxWeight:5000}
  queue1: ${queue1:celery}
  queue2: ${queue2:celery}

logging:
  level:
    org:
      springframework:
        amqp: debug
