spring:
  application:
    name: rabbitmq-listener

management:
  endpoints:
    web:
      exposure:
        include: health,beans
  health:
    rabbit:
      enabled: true
      show-details: always  # Set to 'always' to show more details


rabbitmq:
  host: ${host:localhost}
  port: ${port:5672}
  username: ${username:guest}
  password: ${password:guest}
  concurrentConsumers: ${concurrentConsumers:2}
  maxConcurrentConsumers: ${maxConcurrentConsumers:5}
  enableVirtualThreads: ${enableVirtualThreads:true}
  batchSize: ${batchSize:10}
  batchReceiveTimeout: ${batchReceiveTimeout:5000}
  acknowledgeMode: ${acknowledgeMode:MANUAL}

consumer:
  queue:
    fault: celery
    asset: assets
    reading: reading


logging:
  level:
    org:
      springframework:
        amqp: debug
